# Generated by Django 5.2.5 on 2025-08-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='nomor_telepon',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='posisi',
        ),
        migrations.AddField(
            model_name='absensi',
            name='foto_keluar',
            field=models.ImageField(blank=True, null=True, upload_to='absensi_photos/keluar/'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='foto_masuk',
            field=models.ImageField(blank=True, null=True, upload_to='absensi_photos/masuk/'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='lokasi_keluar_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='lokasi_keluar_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='lokasi_masuk_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='lokasi_masuk_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='divisi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='karyawan_photos/'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
