# Generated by Django 5.2.5 on 2025-08-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0003_karyawan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='foto_absen',
            field=models.ImageField(blank=True, null=True, upload_to='absensi_photos/absen/'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='jam_absen',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='lokasi_absen_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='lokasi_absen_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
