# Generated by Django 5.2.5 on 2025-08-26 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0004_absensi_foto_absen_absensi_jam_absen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absensi',
            old_name='tanggal',
            new_name='tanggal_absen',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='jam_absen',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='jam_keluar',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='jam_masuk',
        ),
        migrations.AddField(
            model_name='absensi',
            name='status_absen',
            field=models.CharField(choices=[('HADIR', 'Hadir'), ('TIDAK HADIR', 'Tidak Hadir')], default='HADIR', max_length=20),
        ),
        migrations.AddField(
            model_name='absensi',
            name='status_keluar',
            field=models.CharField(choices=[('HADIR', 'Hadir'), ('TIDAK HADIR', 'Tidak Hadir')], default='HADIR', max_length=20),
        ),
        migrations.AddField(
            model_name='absensi',
            name='status_masuk',
            field=models.CharField(choices=[('HADIR', 'Hadir'), ('TIDAK HADIR', 'Tidak Hadir')], default='HADIR', max_length=20),
        ),
        migrations.AddField(
            model_name='absensi',
            name='tanggal_keluar',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='tanggal_masuk',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
