# Generated by Django 5.2.5 on 2025-08-27 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0005_rename_tanggal_absensi_tanggal_absen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absensi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status_absen',
            field=models.CharField(blank=True, choices=[('ON_TIME', 'On Time'), ('LATE', 'Telat'), ('IZIN', 'Izin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status_keluar',
            field=models.CharField(blank=True, choices=[('ON_TIME', 'On Time'), ('LATE', 'Telat'), ('IZIN', 'Izin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status_masuk',
            field=models.CharField(blank=True, choices=[('ON_TIME', 'On Time'), ('LATE', 'Telat'), ('IZIN', 'Izin')], max_length=20, null=True),
        ),
    ]
