# Generated by Django 5.2.5 on 2025-08-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0006_absensi_created_at_absensi_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='updated_at',
        ),
    ]
