# Generated by Django 5.2.5 on 2025-08-27 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0007_remove_absensi_created_at_remove_absensi_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absensi',
            old_name='tanggal_absen',
            new_name='tanggal',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='tanggal_keluar',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='tanggal_masuk',
        ),
        migrations.AddField(
            model_name='absensi',
            name='jam_absen',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absensi',
            name='jam_keluar',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='jam_masuk',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absensi',
            name='lokasi_absen_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='lokasi_absen_long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='lokasi_keluar_lat',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='lokasi_keluar_long',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='lokasi_masuk_lat',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='lokasi_masuk_long',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
    ]
