# Generated by Django 5.2.5 on 2025-08-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0008_rename_tanggal_absen_absensi_tanggal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='lokasi_keluar_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='lokasi_keluar_long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='lokasi_masuk_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='lokasi_masuk_long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=16, null=True),
        ),
    ]
