# Generated by Django 5.2.5 on 2025-08-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0009_alter_absensi_lokasi_keluar_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='jam_absen',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_keluar',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_masuk',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
