# Generated by Django 5.2.5 on 2025-09-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0010_alter_absensi_jam_absen_alter_absensi_jam_keluar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='status_absen',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Telat', 'Telat'), ('Absen', 'Absen')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status_keluar',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Telat', 'Telat'), ('Absen', 'Absen')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status_masuk',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Telat', 'Telat'), ('Absen', 'Absen')], max_length=20, null=True),
        ),
    ]
