# Generated by Django 5.2.5 on 2025-09-10 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0011_alter_absensi_status_absen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('alasan', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Disetujui'), ('Rejected', 'Ditolak')], default='Pending', max_length=20)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.karyawan')),
            ],
        ),
    ]
