# Generated by Django 5.2.5 on 2025-09-10 04:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0012_cuti'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuti',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
