# Generated by Django 5.2.5 on 2025-09-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0013_cuti_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='tanggal_lahir',
        ),
    ]
