# Generated by Django 5.2.5 on 2025-09-15 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0014_remove_karyawan_alamat_remove_karyawan_tanggal_lahir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='foto_absen',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='jam_absen',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='lokasi_absen_lat',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='lokasi_absen_long',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='status_absen',
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status_keluar',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Telat', 'Telat')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status_masuk',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Telat', 'Telat')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('Cuti', 'Cuti'), ('Izin', 'Izin'), ('Sakit', 'Sakit')], max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('alasan', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Disetujui'), ('Rejected', 'Ditolak')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeoff', to='absensi.karyawan')),
            ],
        ),
        migrations.DeleteModel(
            name='Cuti',
        ),
    ]
