# Generated by Django 5.2.5 on 2025-09-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0015_remove_absensi_foto_absen_remove_absensi_jam_absen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='jatah_cuti_per_bulan',
            field=models.IntegerField(default=3),
        ),
    ]
