# Generated by Django 5.2.5 on 2025-09-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0016_karyawan_jatah_cuti_per_bulan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
