# Generated by Django 5.2.5 on 2025-09-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0017_alter_timeoff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='jatah_cuti_per_bulan',
            field=models.IntegerField(default=4),
        ),
    ]
