# Generated by Django 5.2.5 on 2025-09-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0020_alter_karyawan_jatah_cuti_per_bulan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='jatah_cuti_per_bulan',
            field=models.IntegerField(default=5),
        ),
    ]
