# Generated by Django 5.2.5 on 2025-09-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0021_alter_karyawan_jatah_cuti_per_bulan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='jatah_cuti_per_bulan',
        ),
    ]
