# Generated by Django 5.2.6 on 2025-09-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0026_karyawan_jatah_cuti_per_bulan'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='perusahaan',
            field=models.CharField(default='PT PAL Indonesia (PERSERO)', max_length=255),
        ),
    ]
