# Generated by Django 5.2.7 on 2025-10-02 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0027_karyawan_perusahaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
                ('kode', models.CharField(help_text='Kode singkat perusahaan (contoh: PAL)', max_length=10, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perusahaan',
                'verbose_name_plural': 'Perusahaan',
                'ordering': ['nama'],
            },
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='perusahaan',
        ),
        migrations.AddField(
            model_name='karyawan',
            name='perusahaan_temp',
            field=models.CharField(blank=True, default='PT PAL Indonesia (PERSERO)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawan', to='absensi.perusahaan'),
        ),
    ]
