# Generated by Django 5.2.7 on 2025-10-02 04:15

from django.db import migrations

def create_companies_and_update_karyawan(apps, schema_editor):
    """Buat perusahaan default dan update karyawan"""
    Perusahaan = apps.get_model('absensi', 'Perusahaan')
    Karyawan = apps.get_model('absensi', 'Karyawan')
    
    # Buat perusahaan default
    perusahaan_list = [
        {'nama': 'PT PAL Indonesia (PERSERO)', 'kode': 'PAL'},
        {'nama': 'PT Telkom Indonesia', 'kode': 'TELKOM'},
        {'nama': 'PT Bank Negara Indonesia', 'kode': 'BNI'},
        {'nama': 'PT Pertamina', 'kode': 'PERTAMINA'},
    ]
    
    created_companies = {}
    for perusahaan_data in perusahaan_list:
        company, created = Perusahaan.objects.get_or_create(
            nama=perusahaan_data['nama'],
            defaults={'kode': perusahaan_data['kode']}
        )
        created_companies[perusahaan_data['nama']] = company
    
    # Update semua karyawan untuk menggunakan perusahaan default
    default_company = created_companies['PT PAL Indonesia (PERSERO)']
    
    for karyawan in Karyawan.objects.all():
        if karyawan.perusahaan_temp in created_companies:
            karyawan.company = created_companies[karyawan.perusahaan_temp]
        else:
            karyawan.company = default_company
        karyawan.save()

def reverse_migration(apps, schema_editor):
    """Rollback function"""
    Perusahaan = apps.get_model('absensi', 'Perusahaan')
    Perusahaan.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0028_perusahaan_remove_karyawan_perusahaan_and_more'),
    ]

    operations = [
        migrations.RunPython(create_companies_and_update_karyawan, reverse_migration),
    ]
