# Generated by Django 5.2.7 on 2025-10-02 04:18

import django.db.models.deletion
from django.db import migrations, models

def copy_company_to_perusahaan(apps, schema_editor):
    """Copy data dari field company ke perusahaan baru"""
    Karyawan = apps.get_model('absensi', 'Karyawan')
    
    # Update semua karyawan dengan company_id yang ada
    for karyawan in Karyawan.objects.all():
        if hasattr(karyawan, 'company') and karyawan.company:
            # Akan diset via raw SQL karena field belum ada di model level
            schema_editor.execute(
                "UPDATE absensi_karyawan SET perusahaan_id = %s WHERE id = %s",
                [karyawan.company.id, karyawan.id]
            )

def reverse_copy(apps, schema_editor):
    """Reverse function"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0029_auto_20251002_1115'),
    ]

    operations = [
        # Tambah field perusahaan dulu dengan nullable
        migrations.AddField(
            model_name='karyawan',
            name='perusahaan',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawan_new', to='absensi.perusahaan'),
        ),
        # Copy data
        migrations.RunPython(copy_company_to_perusahaan, reverse_copy),
        # Hapus field lama
        migrations.RemoveField(
            model_name='karyawan',
            name='company',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='perusahaan_temp',
        ),
        # Ubah field perusahaan jadi non-nullable dan ganti related_name
        migrations.AlterField(
            model_name='karyawan',
            name='perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan', to='absensi.perusahaan'),
        ),
    ]
