# Generated by Django 5.2.7 on 2025-10-09 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0030_remove_karyawan_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
