# Generated by Django 5.2.7 on 2025-10-09 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0031_alter_absensi_tanggal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('TIME_MANIPULATION', 'Manipulasi Waktu'), ('LOCATION_MISMATCH', 'Lokasi Tidak Sesuai'), ('SUSPICIOUS_LOGIN', 'Login Mencurigakan'), ('DUPLICATE_ATTEMPT', 'Percobaan Duplikat'), ('SYSTEM_VALIDATION', 'Validasi Sistem')], max_length=30)),
                ('description', models.TextField()),
                ('client_time', models.TimeField(blank=True, null=True)),
                ('server_time', models.TimeField(blank=True, null=True)),
                ('time_difference_minutes', models.IntegerField(blank=True, null=True)),
                ('client_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=16, null=True)),
                ('client_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=16, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Rendah'), ('MEDIUM', 'Menengah'), ('HIGH', 'Tinggi'), ('CRITICAL', 'Kritis')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Review'), ('REVIEWED', 'Sudah Direview'), ('RESOLVED', 'Teratasi'), ('FALSE_POSITIVE', 'False Positive')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.karyawan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Audit Keamanan',
                'verbose_name_plural': 'Log Audit Keamanan',
                'ordering': ['-created_at'],
            },
        ),
    ]
