# Generated by Django 5.2.5 on 2025-10-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0032_securityauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='alasan_keterlambatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
