# Generated by Django 5.2.5 on 2025-10-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0033_absensi_alasan_keterlambatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='alasan_pulang_cepat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
