# Generated by Django 5.2.5 on 2025-10-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0035_alter_absensi_status_keluar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='status_keluar',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Pulang Cepat', 'Pulang Cepat')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status_masuk',
            field=models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Telat', 'Telat')], max_length=20, null=True),
        ),
    ]
