# Generated by Django 5.2.5 on 2025-10-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0037_alter_karyawan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='jatah_cuti_per_bulan',
        ),
        migrations.AddField(
            model_name='karyawan',
            name='jatah_cuti_per_tahun',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
