# Generated by Django 5.2.7 on 2025-10-16 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0038_remove_karyawan_jatah_cuti_per_bulan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username untuk login ke Django Admin', max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('direktur', 'Direktur'), ('hrd', 'HRD')], help_text='Role: direktur atau hrd', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Apakah admin ini aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perusahaan', models.ForeignKey(help_text='Perusahaan yang dikelola', on_delete=django.db.models.deletion.CASCADE, to='absensi.perusahaan')),
                ('user', models.OneToOneField(blank=True, help_text='User Django yang terhubung (dibuat otomatis)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admin',
                'ordering': ['username'],
            },
        ),
    ]
