# Generated by Django 5.2.7 on 2025-10-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0039_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['username'], 'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='jenis',
            field=models.CharField(choices=[('Cuti', 'Cuti'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Dinas', 'Dinas')], max_length=20),
        ),
    ]
