# Generated by Django 5.2.7 on 2025-10-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0040_alter_admin_options_alter_timeoff_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='jabatan',
            field=models.CharField(choices=[('direktur', 'Direktur'), ('karyawan', 'Karyawan'), ('guru', 'Guru')], default='karyawan', max_length=20),
        ),
    ]
