# Generated by Django 5.2.5 on 2025-10-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0041_karyawan_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='status_lokasi',
            field=models.CharField(blank=True, choices=[('Di Dalam Area PT PAL', 'Di Dalam Area PT PAL'), ('Di Luar Area PT PAL', 'Di Luar Area PT PAL')], help_text='Status lokasi absensi (di dalam/luar area PT PAL)', max_length=50, null=True),
        ),
    ]
