# Generated by Django 5.2.5 on 2025-11-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0042_absensi_status_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='force_password_change',
            field=models.BooleanField(default=True, help_text='User harus ganti password saat login pertama atau setelah reset'),
        ),
        migrations.AddField(
            model_name='admin',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='TOTP sudah di-setup atau belum'),
        ),
    ]
