--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-09-12 09:28:02

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 243 (class 1259 OID 16614)
-- Name: absensi_absensi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.absensi_absensi (
    id bigint NOT NULL,
    tanggal date NOT NULL,
    karyawan_id bigint NOT NULL,
    foto_keluar character varying(100),
    foto_masuk character varying(100),
    lokasi_keluar_lat numeric(16,7),
    lokasi_keluar_long numeric(16,7),
    lokasi_masuk_lat numeric(16,7),
    lokasi_masuk_long numeric(16,7),
    foto_absen character varying(100),
    lokasi_absen_lat numeric(16,7),
    lokasi_absen_long numeric(16,7),
    status_absen character varying(20),
    status_keluar character varying(20),
    status_masuk character varying(20),
    jam_absen time without time zone,
    jam_keluar time without time zone,
    jam_masuk time without time zone
);


ALTER TABLE public.absensi_absensi OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16613)
-- Name: absensi_absensi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.absensi_absensi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.absensi_absensi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 16709)
-- Name: absensi_cuti; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.absensi_cuti (
    id bigint NOT NULL,
    tanggal_mulai date NOT NULL,
    tanggal_selesai date NOT NULL,
    alasan text NOT NULL,
    status character varying(20) NOT NULL,
    karyawan_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.absensi_cuti OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 16708)
-- Name: absensi_cuti_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.absensi_cuti ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.absensi_cuti_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16604)
-- Name: absensi_karyawan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.absensi_karyawan (
    id bigint NOT NULL,
    nama character varying(255) NOT NULL,
    email character varying(254) NOT NULL,
    divisi character varying(255),
    foto_profil character varying(100),
    user_id integer NOT NULL
);


ALTER TABLE public.absensi_karyawan OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16603)
-- Name: absensi_karyawan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.absensi_karyawan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.absensi_karyawan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    password text NOT NULL
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.admin_id_seq OWNER TO postgres;

--
-- TOC entry 5037 (class 0 OID 0)
-- Dependencies: 217
-- Name: admin_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.admin_id_seq OWNED BY public.admin.id;


--
-- TOC entry 228 (class 1259 OID 16479)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16478)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16487)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16486)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16473)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16472)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16493)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16501)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16500)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16492)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16507)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16506)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 16634)
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16565)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16564)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16465)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16464)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16457)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16456)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16593)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16401)
-- Name: locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations (
    id bigint NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    address text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.locations OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16400)
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.locations_id_seq OWNER TO postgres;

--
-- TOC entry 5038 (class 0 OID 0)
-- Dependencies: 219
-- Name: locations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.locations_id_seq OWNED BY public.locations.id;


--
-- TOC entry 4768 (class 2604 OID 16393)
-- Name: admin id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin ALTER COLUMN id SET DEFAULT nextval('public.admin_id_seq'::regclass);


--
-- TOC entry 4769 (class 2604 OID 16404)
-- Name: locations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations ALTER COLUMN id SET DEFAULT nextval('public.locations_id_seq'::regclass);


--
-- TOC entry 5028 (class 0 OID 16614)
-- Dependencies: 243
-- Data for Name: absensi_absensi; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.absensi_absensi (id, tanggal, karyawan_id, foto_keluar, foto_masuk, lokasi_keluar_lat, lokasi_keluar_long, lokasi_masuk_lat, lokasi_masuk_long, foto_absen, lokasi_absen_lat, lokasi_absen_long, status_absen, status_keluar, status_masuk, jam_absen, jam_keluar, jam_masuk) VALUES
  (9, '2025-08-29', 1, 'absensi_photos/keluar/temp_upload_1756464045205.jpg', 'absensi_photos/masuk/temp_upload_1756432387727.jpg', -7.2000722, 112.7433309, -7.2000722, 112.7433309, '', NULL, NULL, NULL, 'On Time', 'On Time', NULL, '15:40:00', '06:53:00'),
  (7, '2025-08-28', 1, '', 'absensi_photos/masuk/temp_upload_1756343647071.jpg', NULL, NULL, -7.2049024, 112.7410963, '', NULL, NULL, NULL, NULL, 'Telat', NULL, NULL, '08:14:00'),
  (10, '2025-09-04', 1, '', '', NULL, NULL, NULL, NULL, 'absensi_photos/absen/temp_upload_1756965744300.jpg', -7.3084803, 112.5952176, 'Absen', NULL, NULL, '13:02:00', NULL, NULL),
  (11, '2025-09-08', 3, '', 'absensi_photos/masuk/temp_upload_1757294659409.jpg', NULL, NULL, -7.2000722, 112.7433309, '', NULL, NULL, NULL, NULL, 'Telat', NULL, NULL, '08:24:00'),
  (12, '2025-09-11', 1, '', 'absensi_photos/masuk/temp_upload_1757556572660.jpg', NULL, NULL, -7.2053840, 112.7415996, '', NULL, NULL, NULL, NULL, 'Telat', NULL, NULL, '09:09:00');


--
-- TOC entry 5031 (class 0 OID 16709)
-- Dependencies: 246
-- Data for Name: absensi_cuti; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5026 (class 0 OID 16604)
-- Dependencies: 241
-- Data for Name: absensi_karyawan; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.absensi_karyawan (id, nama, email, divisi, foto_profil, user_id) VALUES
  (1, 'Ingmareza Nistyo Athallah', 'imareza107@gmail.com', 'Teknologi Informasi', 'karyawan_photos/foto.jpg', 3),
  (3, 'Muizuddin Ahmad Gani', 'blablabla@gmail.com', 'Teknologi Informasi', 'karyawan_photos/gani_chan.jpg', 4),
  (4, 'Danish Nadia Abidin', 'danishnadia@gmail.com', 'Teknologi Informasi', 'karyawan_photos/nadiaa.jpg', 5);


--
-- TOC entry 5003 (class 0 OID 16390)
-- Dependencies: 218
-- Data for Name: admin; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5013 (class 0 OID 16479)
-- Dependencies: 228
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5015 (class 0 OID 16487)
-- Dependencies: 230
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5011 (class 0 OID 16473)
-- Dependencies: 226
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES
  (1, 'Can add log entry', 1, 'add_logentry'),
  (2, 'Can change log entry', 1, 'change_logentry'),
  (3, 'Can delete log entry', 1, 'delete_logentry'),
  (4, 'Can view log entry', 1, 'view_logentry'),
  (5, 'Can add permission', 2, 'add_permission'),
  (6, 'Can change permission', 2, 'change_permission'),
  (7, 'Can delete permission', 2, 'delete_permission'),
  (8, 'Can view permission', 2, 'view_permission'),
  (9, 'Can add group', 3, 'add_group'),
  (10, 'Can change group', 3, 'change_group'),
  (11, 'Can delete group', 3, 'delete_group'),
  (12, 'Can view group', 3, 'view_group'),
  (13, 'Can add user', 4, 'add_user'),
  (14, 'Can change user', 4, 'change_user'),
  (15, 'Can delete user', 4, 'delete_user'),
  (16, 'Can view user', 4, 'view_user'),
  (17, 'Can add content type', 5, 'add_contenttype'),
  (18, 'Can change content type', 5, 'change_contenttype'),
  (19, 'Can delete content type', 5, 'delete_contenttype'),
  (20, 'Can view content type', 5, 'view_contenttype'),
  (21, 'Can add session', 6, 'add_session'),
  (22, 'Can change session', 6, 'change_session'),
  (23, 'Can delete session', 6, 'delete_session'),
  (24, 'Can view session', 6, 'view_session'),
  (25, 'Can add karyawan', 7, 'add_karyawan'),
  (26, 'Can change karyawan', 7, 'change_karyawan'),
  (27, 'Can delete karyawan', 7, 'delete_karyawan'),
  (28, 'Can view karyawan', 7, 'view_karyawan'),
  (29, 'Can add absensi', 8, 'add_absensi'),
  (30, 'Can change absensi', 8, 'change_absensi'),
  (31, 'Can delete absensi', 8, 'delete_absensi'),
  (32, 'Can view absensi', 8, 'view_absensi'),
  (33, 'Can add Token', 9, 'add_token'),
  (34, 'Can change Token', 9, 'change_token'),
  (35, 'Can delete Token', 9, 'delete_token'),
  (36, 'Can view Token', 9, 'view_token'),
  (37, 'Can add Token', 10, 'add_tokenproxy'),
  (38, 'Can change Token', 10, 'change_tokenproxy'),
  (39, 'Can delete Token', 10, 'delete_tokenproxy'),
  (40, 'Can view Token', 10, 'view_tokenproxy'),
  (41, 'Can add cuti', 11, 'add_cuti'),
  (42, 'Can change cuti', 11, 'change_cuti'),
  (43, 'Can delete cuti', 11, 'delete_cuti'),
  (44, 'Can view cuti', 11, 'view_cuti');


--
-- TOC entry 5017 (class 0 OID 16493)
-- Dependencies: 232
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES
  (2, 'pbkdf2_sha256$1000000$lr5sw0YPXdBHOWnf2TEchm$ZOVVAWaikVVWC+YZAhCeQrTo3is5bY+4kG5d2vVagmE=', '2025-08-25 10:24:48.014873+07', 't', 'imare', '', '', 'imareza107@gmail.com', 't', 't', '2025-08-18 11:04:58.829957+07'),
  (3, 'pbkdf2_sha256$1000000$kvPdshPXWgvPasjgzR3Mt6$nuDodymHfUfcbHxQtdrk35DGKEcEwDxhDQIx+pt5u5Q=', NULL, 'f', 123456, 'Ingmareza', 'Nistyo Athallah', 'imareza107@gmail.com', 'f', 't', '2025-08-18 16:02:34+07'),
  (4, 'pbkdf2_sha256$1000000$gTxRVYf3IZE7LTBC7XMipR$BQz6HHFJ4tn9OwShkINZ++QYQc4FpA/5ZHxo+3edQ+Y=', NULL, 'f', 23051204109, 'Muizuddin', 'Ahmad Gani', 'blablabla@gmail.com', 'f', 't', '2025-08-27 09:19:18+07'),
  (5, 'pbkdf2_sha256$1000000$RXKhi1vFcOsGz9YPeJbDAQ$xYM9cYlnlGqumzJNjzlo4LooxjV/zCeYg89UxORrFz0=', NULL, 'f', 23082006, '', '', '', 'f', 't', '2025-09-03 13:21:49.648184+07'),
  (1, 'pbkdf2_sha256$1000000$fumn7EGyULIYTAWAChkAZA$0B6c+QlPOpPFSnaqBkQ/MNjDRbIFlXn0b0MMA0JHEVQ=', '2025-09-11 08:38:19.571815+07', 't', 'imareza', '', '', 'imareza107@gmail.com', 't', 't', '2025-08-18 10:29:03.830531+07');


--
-- TOC entry 5019 (class 0 OID 16501)
-- Dependencies: 234
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5021 (class 0 OID 16507)
-- Dependencies: 236
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5029 (class 0 OID 16634)
-- Dependencies: 244
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5023 (class 0 OID 16565)
-- Dependencies: 238
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) VALUES
  (1, '2025-08-18 14:29:47.808081+07', 1, 'Ingmareza Nistyo Athallah', 1, '[{"added": {}}]', 7, 2),
  (2, '2025-08-18 16:02:35.328944+07', 3, 123456, 1, '[{"added": {}}]', 4, 2),
  (3, '2025-08-18 16:04:06.894052+07', 2, 'Bapak Reza', 1, '[{"added": {}}]', 7, 2),
  (4, '2025-08-25 15:44:51.367056+07', 2, 'Bapak Reza', 2, '[{"changed": {"fields": ["User"]}}]', 7, 2),
  (5, '2025-08-25 15:45:06.945065+07', 1, 'Ingmareza Nistyo Athallah', 2, '[{"changed": {"fields": ["User", "Foto profil"]}}]', 7, 2),
  (6, '2025-08-26 13:18:37.382036+07', 3, 123456, 2, '[{"changed": {"fields": ["password"]}}]', 4, 2),
  (7, '2025-08-26 13:18:55.731747+07', 3, '7e464c544634db9eda2abe65fb38d47bdc9a3997', 1, '[{"added": {}}]', 10, 2),
  (8, '2025-08-26 13:19:21.025593+07', 1, 'Ingmareza Nistyo Athallah', 2, '[]', 7, 2),
  (9, '2025-08-26 13:19:45.295587+07', 3, 123456, 2, '[{"changed": {"fields": ["First name", "Last name", "Email address"]}}]', 4, 2),
  (10, '2025-08-26 13:30:42.383138+07', 1, 'Ingmareza Nistyo Athallah', 2, '[]', 7, 2),
  (11, '2025-08-26 13:30:50.153713+07', 3, '7e464c544634db9eda2abe65fb38d47bdc9a3997', 3, '', 10, 2),
  (12, '2025-08-27 08:34:05.179956+07', 2, 'Bapak Reza', 3, '', 7, 1),
  (13, '2025-08-27 09:08:59.852228+07', 3, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-27', 1, '[{"added": {}}]', 8, 1),
  (14, '2025-08-27 09:10:33.993984+07', 3, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-27', 2, '[{"changed": {"fields": ["Lokasi masuk long", "Lokasi keluar long"]}}]', 8, 1),
  (15, '2025-08-27 09:10:38.722874+07', 3, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-27', 2, '[]', 8, 1),
  (16, '2025-08-27 09:19:19.002184+07', 4, 23051204109, 1, '[{"added": {}}]', 4, 1),
  (17, '2025-08-27 09:22:21.108112+07', 4, 23051204109, 2, '[{"changed": {"fields": ["First name", "Last name", "Email address"]}}]', 4, 1),
  (18, '2025-08-27 09:23:14.796281+07', 3, 'Muizuddin Ahmad Gani', 1, '[{"added": {}}]', 7, 1),
  (19, '2025-08-27 09:29:42.64335+07', 3, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-27', 2, '[{"changed": {"fields": ["Foto masuk", "Foto keluar"]}}]', 8, 1),
  (20, '2025-08-27 10:06:11.731371+07', 3, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-27', 3, '', 8, 1),
  (21, '2025-08-28 11:27:46.127958+07', 5, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-28', 3, '', 8, 1),
  (22, '2025-08-28 13:11:06.42408+07', 6, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-28', 2, '[]', 8, 1),
  (23, '2025-08-28 13:12:20.700019+07', 6, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-28', 3, '', 8, 1),
  (24, '2025-08-29 08:52:01.693466+07', 8, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-29', 3, '', 8, 1),
  (25, '2025-08-29 13:08:06.91822+07', 9, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-29', 2, '[{"changed": {"fields": ["Jam masuk", "Jam keluar"]}}]', 8, 1),
  (26, '2025-08-29 13:08:53.866138+07', 9, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-29', 2, '[{"changed": {"fields": ["Status masuk", "Status keluar"]}}]', 8, 1),
  (27, '2025-08-29 14:12:36.324997+07', 9, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-29', 2, '[{"changed": {"fields": ["Status masuk", "Status keluar"]}}]', 8, 1),
  (28, '2025-09-02 13:41:13.062047+07', 7, 'Absensi Ingmareza Nistyo Athallah pada 2025-08-28', 2, '[{"changed": {"fields": ["Status masuk"]}}]', 8, 1),
  (29, '2025-09-03 13:21:50.125721+07', 5, 23082006, 1, '[{"added": {}}]', 4, 1),
  (30, '2025-09-03 13:23:34.99239+07', 4, 'Danish Nadia Abidin', 1, '[{"added": {}}]', 7, 1);


--
-- TOC entry 5009 (class 0 OID 16465)
-- Dependencies: 224
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.django_content_type (id, app_label, model) VALUES
  (1, 'admin', 'logentry'),
  (2, 'auth', 'permission'),
  (3, 'auth', 'group'),
  (4, 'auth', 'user'),
  (5, 'contenttypes', 'contenttype'),
  (6, 'sessions', 'session'),
  (7, 'absensi', 'karyawan'),
  (8, 'absensi', 'absensi'),
  (9, 'authtoken', 'token'),
  (10, 'authtoken', 'tokenproxy'),
  (11, 'absensi', 'cuti');


--
-- TOC entry 5007 (class 0 OID 16457)
-- Dependencies: 222
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.django_migrations (id, app, name, applied) VALUES
  (1, 'contenttypes', '0001_initial', '2025-08-18 10:26:28.933369+07'),
  (2, 'auth', '0001_initial', '2025-08-18 10:26:28.97917+07'),
  (3, 'admin', '0001_initial', '2025-08-18 10:26:28.989676+07'),
  (4, 'admin', '0002_logentry_remove_auto_add', '2025-08-18 10:26:28.993852+07'),
  (5, 'admin', '0003_logentry_add_action_flag_choices', '2025-08-18 10:26:28.998254+07'),
  (6, 'contenttypes', '0002_remove_content_type_name', '2025-08-18 10:26:29.010098+07'),
  (7, 'auth', '0002_alter_permission_name_max_length', '2025-08-18 10:26:29.015304+07'),
  (8, 'auth', '0003_alter_user_email_max_length', '2025-08-18 10:26:29.020367+07'),
  (9, 'auth', '0004_alter_user_username_opts', '2025-08-18 10:26:29.025634+07'),
  (10, 'auth', '0005_alter_user_last_login_null', '2025-08-18 10:26:29.031164+07'),
  (11, 'auth', '0006_require_contenttypes_0002', '2025-08-18 10:26:29.032148+07'),
  (12, 'auth', '0007_alter_validators_add_error_messages', '2025-08-18 10:26:29.035972+07'),
  (13, 'auth', '0008_alter_user_username_max_length', '2025-08-18 10:26:29.046326+07'),
  (14, 'auth', '0009_alter_user_last_name_max_length', '2025-08-18 10:26:29.051445+07'),
  (15, 'auth', '0010_alter_group_name_max_length', '2025-08-18 10:26:29.058061+07'),
  (16, 'auth', '0011_update_proxy_permissions', '2025-08-18 10:26:29.062595+07'),
  (17, 'auth', '0012_alter_user_first_name_max_length', '2025-08-18 10:26:29.067912+07'),
  (18, 'sessions', '0001_initial', '2025-08-18 10:26:29.073424+07'),
  (19, 'absensi', '0001_initial', '2025-08-18 11:11:36.455139+07'),
  (20, 'absensi', '0002_remove_karyawan_nomor_telepon_remove_karyawan_posisi_and_more', '2025-08-18 14:20:23.569466+07'),
  (21, 'absensi', '0003_karyawan_user', '2025-08-18 15:15:09.355401+07'),
  (22, 'authtoken', '0001_initial', '2025-08-19 14:41:09.374888+07'),
  (23, 'authtoken', '0002_auto_20160226_1747', '2025-08-19 14:41:09.394647+07'),
  (24, 'authtoken', '0003_tokenproxy', '2025-08-19 14:41:09.396566+07'),
  (25, 'authtoken', '0004_alter_tokenproxy_options', '2025-08-19 14:41:09.399496+07'),
  (26, 'absensi', '0004_absensi_foto_absen_absensi_jam_absen_and_more', '2025-08-25 07:49:20.646368+07'),
  (27, 'absensi', '0005_rename_tanggal_absensi_tanggal_absen_and_more', '2025-08-26 13:02:10.159008+07'),
  (28, 'absensi', '0006_absensi_created_at_absensi_updated_at_and_more', '2025-08-27 08:22:15.506054+07'),
  (29, 'absensi', '0007_remove_absensi_created_at_remove_absensi_updated_at', '2025-08-27 08:22:15.517883+07'),
  (30, 'absensi', '0008_rename_tanggal_absen_absensi_tanggal_and_more', '2025-08-27 09:08:50.948609+07'),
  (31, 'absensi', '0009_alter_absensi_lokasi_keluar_lat_and_more', '2025-08-27 09:10:28.228592+07'),
  (32, 'absensi', '0010_alter_absensi_jam_absen_alter_absensi_jam_keluar_and_more', '2025-08-28 09:04:43.163619+07'),
  (33, 'absensi', '0011_alter_absensi_status_absen_and_more', '2025-09-01 10:03:37.465165+07'),
  (34, 'absensi', '0012_cuti', '2025-09-10 10:44:18.899837+07'),
  (35, 'absensi', '0013_cuti_created_at', '2025-09-10 11:03:43.503126+07'),
  (36, 'absensi', '0014_remove_karyawan_alamat_remove_karyawan_tanggal_lahir', '2025-09-11 09:26:32.12954+07');


--
-- TOC entry 5024 (class 0 OID 16593)
-- Dependencies: 239
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.django_session (session_key, session_data, expire_date) VALUES
  ('cjtgjdhhrkldhp6s4zyvn6rexhnqnsvt', '.eJxVjEEOwiAQRe_C2hA6MLS4dO8ZyAwMtmpKUtqV8e7apAvd_vfef6lI2zrGrckSp6zOCtTpd2NKD5l3kO8036pOdV6XifWu6IM2fa1ZnpfD_TsYqY3fGskEKAOLRXTYWd8Zg2DFAIKgcKK-FGcTyGB6ttyx9QOlQFjEBfDq_QHDGDdj:1uqn0v:cFIAMRYgmtLGWbOmD-Yod_G0N9BGOzTxcrcTJxJbsUI', '2025-09-09 13:18:37.391157+07'),
  ('rdh3ekiim5qy3e1nogj3uueltdu58bff', '.eJxVjEEOwiAQRe_C2hBgaBGX7nsGwjCDVA0kpV0Z765NutDtf-_9lwhxW0vYOi9hJnERWpx-N4zpwXUHdI_11mRqdV1mlLsiD9rl1Iif18P9Oyixl28NwM6MQIoZEnuDQEyUBh3ZgrHRO8xITo3Z6sEli5rzGTUk9ArZgXh_AP-BOLU:1uqnUh:YEYwnUZ-XPhBk-EwrobSjSNKPvZTfXlMimEztrQMokU', '2025-09-09 13:49:23.72049+07'),
  ('b4zr1o03mqw90w2ag4v7q52z0kg271tz', '.eJxVjEEOwiAQRe_C2hBgaBGX7nsGwjCDVA0kpV0Z765NutDtf-_9lwhxW0vYOi9hJnERWpx-N4zpwXUHdI_11mRqdV1mlLsiD9rl1Iif18P9Oyixl28NwM6MQIoZEnuDQEyUBh3ZgrHRO8xITo3Z6sEli5rzGTUk9ArZgXh_AP-BOLU:1utKXQ:avqg4WM8PsQk_SsCUkkKMZwOkRWWJjpJYgo90mLxch4', '2025-09-16 13:30:40.344323+07'),
  ('19eovw9o34uadvfv3qlue100yllx5r3j', '.eJxVjEEOwiAQRe_C2hBgaBGX7nsGwjCDVA0kpV0Z765NutDtf-_9lwhxW0vYOi9hJnERWpx-N4zpwXUHdI_11mRqdV1mlLsiD9rl1Iif18P9Oyixl28NwM6MQIoZEnuDQEyUBh3ZgrHRO8xITo3Z6sEli5rzGTUk9ArZgXh_AP-BOLU:1utgr9:z4PL_xAEJ5NuqpWy-zY7WqCiT7qIasrbC4cGaW1OyEI', '2025-09-17 13:20:31.905925+07'),
  ('nqo6wgzeid0z2rd9ry89ojrk0ym7b4zk', '.eJxVjEEOwiAQRe_C2hBgaBGX7nsGwjCDVA0kpV0Z765NutDtf-_9lwhxW0vYOi9hJnERWpx-N4zpwXUHdI_11mRqdV1mlLsiD9rl1Iif18P9Oyixl28NwM6MQIoZEnuDQEyUBh3ZgrHRO8xITo3Z6sEli5rzGTUk9ArZgXh_AP-BOLU:1uwWGR:OWAdKbjPm52_hNTE_DZrUl8lDsWWMcb97_OWVEx0FaA', '2025-09-25 08:38:19.57562+07');


--
-- TOC entry 5005 (class 0 OID 16401)
-- Dependencies: 220
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5039 (class 0 OID 0)
-- Dependencies: 242
-- Name: absensi_absensi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.absensi_absensi_id_seq', 12, true);


--
-- TOC entry 5040 (class 0 OID 0)
-- Dependencies: 245
-- Name: absensi_cuti_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.absensi_cuti_id_seq', 1, false);


--
-- TOC entry 5041 (class 0 OID 0)
-- Dependencies: 240
-- Name: absensi_karyawan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.absensi_karyawan_id_seq', 4, true);


--
-- TOC entry 5042 (class 0 OID 0)
-- Dependencies: 217
-- Name: admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_id_seq', 1, false);


--
-- TOC entry 5043 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5044 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5045 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- TOC entry 5046 (class 0 OID 0)
-- Dependencies: 233
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 5047 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 5, true);


--
-- TOC entry 5048 (class 0 OID 0)
-- Dependencies: 235
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5049 (class 0 OID 0)
-- Dependencies: 237
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 30, true);


--
-- TOC entry 5050 (class 0 OID 0)
-- Dependencies: 223
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- TOC entry 5051 (class 0 OID 0)
-- Dependencies: 221
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 36, true);


--
-- TOC entry 5052 (class 0 OID 0)
-- Dependencies: 219
-- Name: locations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.locations_id_seq', 1, false);


--
-- TOC entry 4835 (class 2606 OID 16618)
-- Name: absensi_absensi absensi_absensi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absensi_absensi
    ADD CONSTRAINT absensi_absensi_pkey PRIMARY KEY (id);


--
-- TOC entry 4843 (class 2606 OID 16715)
-- Name: absensi_cuti absensi_cuti_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absensi_cuti
    ADD CONSTRAINT absensi_cuti_pkey PRIMARY KEY (id);


--
-- TOC entry 4828 (class 2606 OID 16612)
-- Name: absensi_karyawan absensi_karyawan_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absensi_karyawan
    ADD CONSTRAINT absensi_karyawan_email_key UNIQUE (email);


--
-- TOC entry 4830 (class 2606 OID 16610)
-- Name: absensi_karyawan absensi_karyawan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absensi_karyawan
    ADD CONSTRAINT absensi_karyawan_pkey PRIMARY KEY (id);


--
-- TOC entry 4832 (class 2606 OID 16628)
-- Name: absensi_karyawan absensi_karyawan_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absensi_karyawan
    ADD CONSTRAINT absensi_karyawan_user_id_key UNIQUE (user_id);


--
-- TOC entry 4774 (class 2606 OID 16397)
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (id);


--
-- TOC entry 4776 (class 2606 OID 16399)
-- Name: admin admin_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_username_key UNIQUE (username);


--
-- TOC entry 4792 (class 2606 OID 16591)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4797 (class 2606 OID 16522)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4800 (class 2606 OID 16491)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4794 (class 2606 OID 16483)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4787 (class 2606 OID 16513)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4789 (class 2606 OID 16477)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4808 (class 2606 OID 16505)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4811 (class 2606 OID 16537)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4802 (class 2606 OID 16497)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4814 (class 2606 OID 16511)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4817 (class 2606 OID 16551)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4805 (class 2606 OID 16586)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4838 (class 2606 OID 16638)
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- TOC entry 4840 (class 2606 OID 16640)
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- TOC entry 4820 (class 2606 OID 16572)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4782 (class 2606 OID 16471)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4784 (class 2606 OID 16469)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4780 (class 2606 OID 16463)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4824 (class 2606 OID 16599)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4778 (class 2606 OID 16410)
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- TOC entry 4833 (class 1259 OID 16625)
-- Name: absensi_absensi_karyawan_id_78c46aa0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX absensi_absensi_karyawan_id_78c46aa0 ON public.absensi_absensi USING btree (karyawan_id);


--
-- TOC entry 4841 (class 1259 OID 16721)
-- Name: absensi_cuti_karyawan_id_a4cc5a41; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX absensi_cuti_karyawan_id_a4cc5a41 ON public.absensi_cuti USING btree (karyawan_id);


--
-- TOC entry 4826 (class 1259 OID 16619)
-- Name: absensi_karyawan_email_07a951ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX absensi_karyawan_email_07a951ec_like ON public.absensi_karyawan USING btree (email varchar_pattern_ops);


--
-- TOC entry 4790 (class 1259 OID 16592)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4795 (class 1259 OID 16533)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4798 (class 1259 OID 16534)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4785 (class 1259 OID 16519)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4806 (class 1259 OID 16549)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4809 (class 1259 OID 16548)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4812 (class 1259 OID 16563)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4815 (class 1259 OID 16562)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4803 (class 1259 OID 16587)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4836 (class 1259 OID 16646)
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- TOC entry 4818 (class 1259 OID 16583)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4821 (class 1259 OID 16584)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4822 (class 1259 OID 16601)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4825 (class 1259 OID 16600)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4854 (class 2606 OID 16620)
-- Name: absensi_absensi absensi_absensi_karyawan_id_78c46aa0_fk_absensi_karyawan_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absensi_absensi
    ADD CONSTRAINT absensi_absensi_karyawan_id_78c46aa0_fk_absensi_karyawan_id FOREIGN KEY (karyawan_id) REFERENCES public.absensi_karyawan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4856 (class 2606 OID 16716)
-- Name: absensi_cuti absensi_cuti_karyawan_id_a4cc5a41_fk_absensi_karyawan_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absensi_cuti
    ADD CONSTRAINT absensi_cuti_karyawan_id_a4cc5a41_fk_absensi_karyawan_id FOREIGN KEY (karyawan_id) REFERENCES public.absensi_karyawan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4853 (class 2606 OID 16629)
-- Name: absensi_karyawan absensi_karyawan_user_id_1eba66f0_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absensi_karyawan
    ADD CONSTRAINT absensi_karyawan_user_id_1eba66f0_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4845 (class 2606 OID 16528)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4846 (class 2606 OID 16523)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4844 (class 2606 OID 16514)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4847 (class 2606 OID 16543)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4848 (class 2606 OID 16538)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4849 (class 2606 OID 16557)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4850 (class 2606 OID 16552)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4855 (class 2606 OID 16641)
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4851 (class 2606 OID 16573)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4852 (class 2606 OID 16578)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-09-12 09:28:03

--
-- PostgreSQL database dump complete
--
