"""
Django settings for absensi_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

ALLOWED_HOSTS = ['192.168.70.101:8081', '172.20.10.6', 'localhost', '192.168.18.18:8000', '*']

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-51y1b!9(@*+u485foojo1(x_ya80o&&4s14q#6_k44!%l)gv$h'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True  # Development mode - show detailed errors
DEBUG = False  # Production mode - hide error details

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'absensi',
    'rest_framework',
    'rest_framework_simplejwt',
    # Two-Factor Authentication (TOTP)
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'two_factor',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'absensi.middleware.ContentSecurityPolicyMiddleware',  # CSP Security Header
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # TOTP Middleware
    'absensi.middleware.ForcePasswordChangeMiddleware',  # Force Password Change for TOTP
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'absensi_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'absensi_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'absensi_db',
        'USER': 'postgres',
        'PASSWORD': '12345',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'absensi.validators.CustomPasswordValidator',  # Custom validator for TOTP requirements
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# CORS settings
# CORS_ALLOW_ALL_ORIGINS = True  # Development only - allow all origins (RISK - disabled for production)
CORS_ALLOW_ALL_ORIGINS = True  # Production - only allow specific origins
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://192.168.18.18:8000",
    "http://192.168.70.101:8081",
]

CORS_ALLOW_CREDENTIALS = True

# Session Configuration untuk Admin Security
SESSION_COOKIE_AGE = 1800  # 30 menit (1800 detik)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expire saat browser ditutup
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session setiap request
SESSION_COOKIE_SECURE = False  # Set True jika menggunakan HTTPS (currently False for development IPs)
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access ke session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# Security settings for production
SECURE_BROWSER_XSS_FILTER = True  # Enable XSS filter
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME-sniffing
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Clickjacking protection

# ============================================
# CONTENT SECURITY POLICY (CSP) CONFIGURATION
# ============================================
# CSP diimplementasikan via middleware: absensi.middleware.ContentSecurityPolicyMiddleware
# CSP melindungi dari XSS attacks dengan membatasi sumber content yang boleh diload
# 
# Path yang dilindungi CSP:
# - /admin (semua subpath admin panel)
# - /admin/login/
# - /robots.txt
# - /sitemap.xml
#
# Security headers tambahan yang diterapkan:
# - X-Content-Type-Options: nosniff (prevent MIME sniffing attacks)
# - X-Frame-Options: SAMEORIGIN (prevent clickjacking)
# - X-XSS-Protection: 1; mode=block (enable browser XSS filter)
# - Referrer-Policy: strict-origin-when-cross-origin (control referrer information)

# ============================================
# TOTP (TWO-FACTOR AUTHENTICATION) CONFIGURATION
# ============================================
# TOTP digunakan untuk HRD dan Direktur roles
# Flow:
# 1. First login: username + default password → force password change → TOTP setup (scan QR)
# 2. Forgot TOTP: superadmin reset → login → scan QR again (no password change)
# 3. Forgot password: superadmin reset → default password → login → force password change → enter TOTP code
# 4. Reset both: full first login flow again
#
# Password requirements:
# - Minimum 9 characters
# - 1 uppercase letter
# - 1 lowercase letter
# - 1 symbol
# - No spaces allowed

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# django-two-factor-auth settings
TWO_FACTOR_PATCH_ADMIN = False  # We'll customize admin ourselves
TWO_FACTOR_CALL_GATEWAY = None
TWO_FACTOR_SMS_GATEWAY = None
